site_name: DSSV Data Conclave FY26 - Vatican Explorer
site_description: Documentation for the DSSV Vatican Explorer
site_url: https://rcds-dssv.github.io/dc26-vatican-explorer

repo_url: https://github.com/rcds-dssv/dc26-vatican-explorer
repo_name: rcds-dssv/dc26-vatican-explorer

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          # since not yet pip installable (but I think this can be removed once it is installable)
          paths: 
            [src]
          options:
            docstring_style: google
            show_source: false

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api.md

