name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main               # Trigger when a PR is merged into main
      - rg-test-gh-deploy  # Trigger on test branch pushes
  workflow_dispatch:       # Trigger manually

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.x"

      - run: uv sync --group docs
      - run: uv run mkdocs gh-deploy --force --clean --verbose
